model:
  num_input_channels: 9
  input_length: 128
  num_classes: 6
  hidden_dim: 128
  kernel_size: 3
  num_levels: 2
  num_layers: 3
  wavelet_type: 'db1'
  feedforward_ratio: 1
  group_type: 'channel'
  normalization_eps: 1e-5
  normalization_affine: True

training:
  batch_size: 32
  num_epochs_per_comm: 20
  learning_rate: 0.001
  validation_split: 0.2
  federated: True
  federated_type: 'fedavg'
  # 其他联邦学习参数...

data:
  dataset_name: "UCI-HAR"  # 当前数据集名称，可以设置为 "WISDM"
  
  UCI-HAR:
    data_dir: "../data/UCI-HAR-Dataset"
    signal_types: ['body_acc_x', 'body_acc_y', 'body_acc_z', 
                  'body_gyro_x', 'body_gyro_y', 'body_gyro_z', 
                  'total_acc_x', 'total_acc_y', 'total_acc_z']
    input_length: 128
    num_classes: 6
    num_input_channels: 9  # 对应于 signal_types 的数量

  WISDM:
    data_dir: "../data/WISDM_ar_v1.1"
    raw_filename: "WISDM_ar_v1.1_raw.txt"
    signal_types: ['x-accel', 'y-accel', 'z-accel']
    input_length: 128
    num_classes: 6
    num_input_channels: 3  # 对应于 signal_types 的数量
    window_size: 128
    step_size: 64
    activity_mapping:
      Walking: 0
      Jogging: 1
      Upstairs: 2
      Downstairs: 3
      Sitting: 4
      Standing: 5
